// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxowjdjubxstctqazafl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4b3dqZGp1YnhzdGN0cWF6YWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDgzMTIsImV4cCI6MjA2MDcyNDMxMn0.iOKITY-PDBSO0gT6Z080MX4InNfRCKb_rLv53x58X4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);